#cloud-config
package_update: true
packages:
  - git
  - curl
  - wget
  - docker.io
  - python3
  - python3-pip
  - openssh-server
  - sqlite3

write_files:
  - path: /usr/local/bin/ti-bootstrap.sh
    permissions: '0755'
    owner: root:root
    content: |
      #!/bin/bash
      set -e
      export HOME=/root
      
      # Install docker-compose
      curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      chmod +x /usr/local/bin/docker-compose
      ln -sf /usr/local/bin/docker-compose /usr/bin/docker-compose
      
      # Clone the repository
      cd /root
      git clone https://github.com/standobrov/tech-interview-service-de.git
      cd tech-interview-service-de
      chmod +x deploy_new.sh cleanup.sh
      
      # Run the full automated setup
      ./deploy_new.sh 2>&1 | tee /root/deployment.log
      
      echo "Bootstrap completed! Check /root/deployment.log for details."

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - sleep 15
  - /usr/local/bin/ti-bootstrap.sh