#cloud-config
write_files:
  - path: /usr/local/bin/ti-bootstrap.sh
    permissions: '0755'
    owner: root:root
    content: |
      #!/bin/bash
      set -e
      export HOME=/root
      if ! command -v git >/dev/null 2>&1; then
        apt-get update -y
        apt-get install -y git
      fi
      cd /root
      git clone https://github.com/standobrov/tech-interview-service-de.git
      cd tech-interview-service-de
      chmod +x setup_repo.sh deploy.sh
      ./setup_codeserver.sh
      ./setup_repo.sh
      ./deploy.sh
      cd /root
      rm -rf tech-interview-service
      rm -f  /root/.bash_history

runcmd:
  - /usr/local/bin/ti-bootstrap.sh